Use bundled comerr, as building against the system one breaks.
default/source4/heimdal/lib/krb5/krb5_err.c:279:23: error: ‘link’ redeclared as different kind of symbol
 static struct et_list link = { 0, 0 };
                       ^
In file included from /usr/include/bsd/unistd.h:31:0,
                 from ../lib/replace/../replace/replace.h:159,
                 from ../source4/heimdal_build/config.h:10,
                 from default/source4/heimdal/lib/krb5/krb5_err.c:1:
/usr/include/unistd.h:790:12: note: previous declaration of ‘link’ was here
 extern int link (const char *__from, const char *__to)
            ^